<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Detail_pemakaian_model extends CI_Model
{

    public $table = 'detail_pemakaian';
    public $id = 'id_pakai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pakai', $q);
	$this->db->or_like('id_pemakaian', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('umum', $q);
	$this->db->or_like('jknpbi', $q);
	$this->db->or_like('jknnonpbi', $q);
	$this->db->or_like('jamkesda', $q);
	$this->db->or_like('jamkesdasktm', $q);
	$this->db->or_like('jamkesdajamkesmas', $q);
	$this->db->or_like('uks', $q);
	$this->db->or_like('kir', $q);
	$this->db->or_like('gratis', $q);
	$this->db->or_like('lainlian', $q);
	$this->db->or_like('jumlah_pemakaian', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pakai', $q);
	$this->db->or_like('id_pemakaian', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('umum', $q);
	$this->db->or_like('jknpbi', $q);
	$this->db->or_like('jknnonpbi', $q);
	$this->db->or_like('jamkesda', $q);
	$this->db->or_like('jamkesdasktm', $q);
	$this->db->or_like('jamkesdajamkesmas', $q);
	$this->db->or_like('uks', $q);
	$this->db->or_like('kir', $q);
	$this->db->or_like('gratis', $q);
	$this->db->or_like('lainlian', $q);
	$this->db->or_like('jumlah_pemakaian', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Detail_pemakaian_model.php */
/* Location: ./application/models/Detail_pemakaian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-30 05:23:34 */
/* http://harviacode.com */